---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shark-info
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shark-app
  template:
    metadata:
      name: shark-pod
      labels:
        app: shark-app
    spec:
      containers:
      - name: shark-container
        image: prempalsingh/devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service 
metadata:
  name: shark-svc
  labels:
    app: shark-app
spec:
  selector:
    app: shark-app
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80